/**
 * @enum PermissionEnum
 * @description Defines the permissions for various actions within the system.
 * This file is auto-generated by a script. Do not edit manually.
 * Last updated: 2025-11-27T15:26:55.261Z
 */
export enum PermissionEnum {
    /** Get list of organizations */
    DEPARTMENTS_LIST = "departments:list",

    /** Get users by organizations */
    USERS_LIST_BY_ORGANIZATION = "users:list_by_organization",

    /** infrastructure:objets_list */
    INFRASTRUCTURE_OBJETS_LIST = "infrastructure:objets_list",

    /** infrastructure:objets_infralist */
    INFRASTRUCTURE_OBJETS_INFRALIST = "infrastructure:objets_infralist",

    /** Getting the list of MTUs */
    INFRASTRUCTURE_MTU_LIST = "infrastructure:mtu_list",

    /** Assign a single permission to a role */
    ROLE_ASSIGN_ONE_PERMISSION = "role:assign_one_permission",

    /** work_type_progresses:add_brigade */
    WORK_TYPE_PROGRESSES_ADD_BRIGADE = "work_type_progresses:add_brigade",

    /** Get organizations */
    ORGANIZATIONS_GET = "organizations:get",

    /** work_type_progresses:attach_plot */
    WORK_TYPE_PROGRESSES_ATTACH_PLOT = "work_type_progresses:attach_plot",

    /** Attach a file to the work type progress */
    WORK_TYPE_PROGRESSES_ATTACHMENT_PLOT = "work_type_progresses:attachment_plot",

    /** Search employees */
    XODIM_SEARCH = "xodim:search",

    /** dynamic_infrastructure:select */
    DYNAMIC_INFRASTRUCTURE_SELECT = "dynamic_infrastructure:select",

    /** dynamic_infrastructure:update */
    DYNAMIC_INFRASTRUCTURE_UPDATE = "dynamic_infrastructure:update",

    /** smeta:list_by_object */
    SMETA_LIST_BY_OBJECT = "smeta:list_by_object",

    /** smeta_progrese:list */
    SMETA_PROGRESE_LIST = "smeta_progrese:list",

    /** smeta_progrese:get */
    SMETA_PROGRESE_GET = "smeta_progrese:get",

    /** smeta_progrese:delete */
    SMETA_PROGRESE_DELETE = "smeta_progrese:delete",

    /** Remove constructors from object */
    OBJECT_REMOVE_CONSTRUCTORS = "object:remove_constructors",

    /** work_type_plan:list */
    WORK_TYPE_PLAN_LIST = "work_type_plan:list",

    /** work_type_plan:update */
    WORK_TYPE_PLAN_UPDATE = "work_type_plan:update",

    /** work_type_plan:delete */
    WORK_TYPE_PLAN_DELETE = "work_type_plan:delete",

    /** Get constructors from object */
    OBJECT_GET_CONSTRUCTORS = "object:get_constructors",

    /** Get contractors list */
    CONSTRUCTOR_GET = "constructor:get",

    /** Employees count statistics */
    PLOT_STATISTICS_EMPLOYEES_COUNT = "plot:statistics_employees_count",

    /** Documents statistics */
    DOCUMENTS_STATISTICS = "documents:statistics",

    /** Approve object documents */
    OBJECT_DOCUMENTS_APPROVE = "object_documents:approve",

    /** Upload object documents */
    OBJECT_DOCUMENTS_UPLOAD = "object_documents:upload",

    /** Add object documents */
    OBJECT_DOCUMENTS_ADD = "object_documents:add",

    /** Select documents by object */
    DOCUMENTS_SELECT_BY_OBJECT = "documents:select_by_object",

    /** Get documents for selector */
    DOCUMENTS_SELECT = "documents:select",

    /** View module */
    PERM_MODULES_VIEW = "perm_modules:view",

    /** Update chief architect */
    CHIEF_ARCHITECTS_UPDATE = "chief_architects:update",

    /** Select chief architect */
    CHIEF_ARCHITECTS_SELECT = "chief_architects:select",

    /** View chief architect */
    CHIEF_ARCHITECTS_VIEW = "chief_architects:view",

    /** Objects dictionary list */
    OBJECTS_DICTIONARY_LIST = "objects:dictionary_list",

    /** Delete customer */
    CUSTOMERS_DELETE = "customers:delete",

    /** Update customer */
    CUSTOMERS_UPDATE = "customers:update",

    /** Get customer */
    CUSTOMERS_GET = "customers:get",

    /** Select customer */
    CUSTOMERS_SELECT = "customers:select",

    /** Customers list */
    CUSTOMERS_LIST = "customers:list",

    /** Create customer */
    CUSTOMERS_CREATE = "customers:create",

    /** Remove inspector from object */
    INSPECTORS_REMOVE = "inspectors:remove",

    /** Inspectors list */
    INSPECTORS_LIST = "inspectors:list",

    /** Add inspector to object */
    INSPECTORS_ADD = "inspectors:add",

    /** Assign one employee to object */
    OBJECT_ASSIGN_ONE_EMPLOYEE = "object:assign_one_employee",

    /** Document progress list */
    DOCUMENT_PROGRESS_LIST = "document_progress:list",

    /** Update document progress */
    DOCUMENT_PROGRESS_UPDATE = "document_progress:update",

    /** Can access settings */
    ROLE_CAN_ACCESS_SETTINGS = "role:can_access_settings",

    /** auth:change-user-password */
    AUTH_CHANGE_USER_PASSWORD = "auth:change-user-password",

    /** auth:reset-user-password */
    AUTH_RESET_USER_PASSWORD = "auth:reset-user-password",

    /** Admin rights */
    CORE_IS_ADMIN = "core:is_admin",

    /** users:remove_user */
    USERS_REMOVE_USER = "users:remove_user",

    /** role:select */
    ROLE_SELECT = "role:select",

    /** Change password */
    AUTH_CHANGE_PASSWORD = "auth:change-password",

    /** Remove user */
    USERS_REMOVE = "users:remove",

    /** Create role */
    ROLE_CREATE = "role:create",

    /** Assign permissions to role */
    ROLE_ASSIGN_PERMISSIONS = "role:assign_permissions",

    /** Remove role */
    ROLE_REMOVE = "role:remove",

    /** Assign user to role */
    ROLE_ASSIGN_USER = "role:assign_user",

    /** Loyiha qo‘shimcha ma’lumotini yangilash */
    OBJECT_UPDATE_VALUE = "object:update_value",

    /** dynamic_infrastructure:create */
    DYNAMIC_INFRASTRUCTURE_CREATE = "dynamic_infrastructure:create",

    /** Loyihani yangilash */
    OBJECT_UPDATE = "object:update",

    /** dynamic_infrastructure:infra_type_select */
    DYNAMIC_INFRASTRUCTURE_INFRA_TYPE_SELECT = "dynamic_infrastructure:infra_type_select",

    /** Loyihalar ro'yxati */
    OBJECT_LIST = "object:list",

    /** Loyihaga qo'shimcha ma'lumot qo'shish */
    OBJECT_CREATE_VALUE = "object:create_value",

    /** Uchastkani yangilash */
    PLOT_UPDATE = "plot:update",

    /** Update organization */
    ORGANIZATIONS_UPDATE = "organizations:update",

    /** Create organization */
    ORGANIZATIONS_CREATE = "organizations:create",

    /** Loyiha qo‘shimcha ma’lumotini o‘chirish */
    OBJECT_DELETE_VALUE = "object:delete_value",

    /** users:remove_user_role_assignment */
    USERS_REMOVE_USER_ROLE_ASSIGNMENT = "users:remove_user_role_assignment",

    /** Infratuzilma */
    INFRASTRUCTURE_GET_BY_ID = "infrastructure:get_by_id",

    /** Create user 3 */
    USERS_CREATE = "users:create",

    /** infrastructure:update */
    INFRASTRUCTURE_UPDATE = "infrastructure:update",

    /** infrastructure:delete */
    INFRASTRUCTURE_DELETE = "infrastructure:delete",

    /** infra-types:create */
    INFRA_TYPES_CREATE = "infra-types:create",

    /** infra-types:update */
    INFRA_TYPES_UPDATE = "infra-types:update",

    /** infra-types:remove */
    INFRA_TYPES_REMOVE = "infra-types:remove",

    /** work_type:create */
    WORK_TYPE_CREATE = "work_type:create",

    /** work_type:list */
    WORK_TYPE_LIST = "work_type:list",

    /** work_type:update */
    WORK_TYPE_UPDATE = "work_type:update",

    /** infra-types:select_parent */
    INFRA_TYPES_SELECT_PARENT = "infra-types:select_parent",

    /** infra-types:select_children */
    INFRA_TYPES_SELECT_CHILDREN = "infra-types:select_children",

    /** work_type:remove */
    WORK_TYPE_REMOVE = "work_type:remove",

    /** work_type_progresses:add_fact */
    WORK_TYPE_PROGRESSES_ADD_FACT = "work_type_progresses:add_fact",

    /** Fetch employees from the E-Xodim platform by PINFL */
    XODIM_GET_BY_PIN = "xodim:get_by_pin",

    /** work_type_progresses:view */
    WORK_TYPE_PROGRESSES_VIEW = "work_type_progresses:view",

    /** work_type_progresses:edit */
    WORK_TYPE_PROGRESSES_EDIT = "work_type_progresses:edit",

    /** work_type_progresses:delete */
    WORK_TYPE_PROGRESSES_DELETE = "work_type_progresses:delete",

    /** work:create */
    WORK_CREATE = "work:create",

    /** work:list */
    WORK_LIST = "work:list",

    /** work:update */
    WORK_UPDATE = "work:update",

    /** work:remove */
    WORK_REMOVE = "work:remove",

    /** work-progress:add-plan */
    WORK_PROGRESS_ADD_PLAN = "work-progress:add-plan",

    /** work-progress:add-fact */
    WORK_PROGRESS_ADD_FACT = "work-progress:add-fact",

    /** smeta:create */
    SMETA_CREATE = "smeta:create",

    /** smeta:get */
    SMETA_GET = "smeta:get",

    /** smeta:delete */
    SMETA_DELETE = "smeta:delete",

    /** smeta:update */
    SMETA_UPDATE = "smeta:update",

    /** View list of users */
    USERS_LIST = "users:list",

    /** Infratuzilmalar ro'yhati */
    INFRASTRUCTURE_LIST = "infrastructure:list",

    /** Create object */
    OBJECT_CREATE = "object:create",

    /** Ruxsatlarni nomini yangilash */
    PERMISSIONS_UPDATE_DESCRIPTION = "permissions:update_description",

    /** Ruxsatlarni modullari bo'yicha olish */
    PERMISSIONS_MODULE_SELECT = "permissions:module_select",

    /** Ruxsatlarni tanlovchi uchun (selector) olish */
    PERMISSIONS_SELECT = "permissions:select",

    /** Ruxsatlarni umumiy ro'yxati */
    PERMISSIONS_LIST = "permissions:list",

    /** Rollarni yangilash */
    ROLE_UPDATE = "role:update",

    /** Rollarning umumiy ro'yxati */
    ROLE_LIST = "role:list",

    /** Foydalanuvchilar ro'yxatini tanlovchi (selector) uchun olish */
    USERS_DICTIONARY_LIST = "users:dictionary_list",

    /** Uchastkadan xodimni o'chirish */
    PLOT_REMOVE_EMPLOYEE = "plot:remove_employee",

    /** Uchastkani o'chirish */
    PLOT_REMOVE = "plot:remove",

    /** Bitta uchastka ma'lumotlarini olish */
    PLOT_GET = "plot:get",

    /** Uchastkalarni ro'yxatini olish */
    PLOT_LIST = "plot:list",

    /** Hujjatni o'chirish */
    DOCUMENTS_REMOVE = "documents:remove",

    /** Hujjatni yangilash */
    DOCUMENTS_UPDATE = "documents:update",

    /** Hujjatlarni ro'yxatini olish */
    DOCUMENTS_LIST = "documents:list",

    /** Yangi hujjat yaratish */
    DOCUMENTS_CREATE = "documents:create",

    /** Hujjat turini o'chirish */
    DOCUMENT_CORE_DELETE = "document-core:delete",

    /** Bitta hujjat turini olish */
    DOCUMENT_CORE_GET = "document-core:get",

    /** Hujjat turini tanlovchi (selector) uchun olish */
    DOCUMENT_CORE_SELECT = "document-core:select",

    /** Hujjatlar ro'yxatini olish */
    DOCUMENT_CORE_LIST = "document-core:list",

    /** O'lchov birligini o'chirish */
    MEASUREMENTS_DELETE = "measurements:delete",

    /** Bitta o'lchov birligini olish */
    MEASUREMENTS_GET_BY_ID = "measurements:get_by_id",

    /** O'lchov birliklarini tanlovchi (selector) uchun olish */
    MEASUREMENTS_DICTIONARY_LIST = "measurements:dictionary_list",

    /** O'lchov birliklari ro'yxatini olish */
    MEASUREMENTS_LIST = "measurements:list",

    /** Loyiha tafsilorlarida rasmni o'chirish */
    PROJECT_DETAILS_DELETE_PHOTO = "project-details:delete-photo",

    /** Loyiha tafsilorlarida rasmni yangilash */
    PROJECT_DETAILS_UPDATE_PHOTO = "project-details:update-photo",

    /** Loyiha tafsilotlari ro'yxatini olish */
    PROJECT_DETAILS_LIST = "project-details:list",

    /** Loyiha ma'sul shaxslaridan xodimini o'chirish */
    OBJECT_REMOVE_EMPLOYEE = "object:remove_employee",

    /** Loyihaga biriktirilgan xodimlar ro‘yxati */
    OBJECT_LIST_EMPLOYEE = "object:list_employee",

    /** Loyihani o'chirish */
    OBJECT_DELETE = "object:delete",

    /** Get organizations list for selector */
    ORGANIZATIONS_SELECT = "organizations:select",

    /** Delete organization */
    ORGANIZATIONS_DELETE = "organizations:delete",

    /** infrastructure:objetslist */
    INFRASTRUCTURE_OBJETSLIST = "infrastructure:objetslist",

    /** infrastructure:objets_inlist */
    INFRASTRUCTURE_OBJETS_INLIST = "infrastructure:objets_inlist",

    /** Get object values */
    OBJECT_GET_VALUES = "object:get_values",

    /** work_type_progresses: */
    WORK_TYPE_PROGRESSES_ = "work_type_progresses:",

    /** work_type_progresses:add_plot */
    WORK_TYPE_PROGRESSES_ADD_PLOT = "work_type_progresses:add_plot",

    /** work_type_progresses:attach_brigade */
    WORK_TYPE_PROGRESSES_ATTACH_BRIGADE = "work_type_progresses:attach_brigade",

    /** Assign constructors to object */
    OBJECT_ASSIGN_CONSTRUCTORS = "object:assign_constructors",

    /** Update user */
    USERS_UPDATE = "users:update",

    /** Update role and permissions */
    ROLE_UPDATE_ROLE_AND_PERMISSIONS = "role:update-role-and-permissions",

    /** dynamic_infrastructure:list */
    DYNAMIC_INFRASTRUCTURE_LIST = "dynamic_infrastructure:list",

    /** dynamic_infrastructure:get */
    DYNAMIC_INFRASTRUCTURE_GET = "dynamic_infrastructure:get",

    /** Employees position count statistics */
    PLOT_STATISTICS_EMPLOYEES_POSITION_COUNT = "plot:statistics_employees_position_count",

    /** smeta_progrese:create */
    SMETA_PROGRESE_CREATE = "smeta_progrese:create",

    /** smeta_progrese:read */
    SMETA_PROGRESE_READ = "smeta_progrese:read",

    /** smeta_progrese:update */
    SMETA_PROGRESE_UPDATE = "smeta_progrese:update",

    /** Update module name */
    PERM_MODULES_UPDATE_NAME = "perm_modules:update_name",

    /** work_type_plan:create */
    WORK_TYPE_PLAN_CREATE = "work_type_plan:create",

    /** work_type_plan:get */
    WORK_TYPE_PLAN_GET = "work_type_plan:get",

    /** organizations-work-type:create */
    ORGANIZATIONS_WORK_TYPE_CREATE = "organizations-work-type:create",

    /** organizations-work-type:update */
    ORGANIZATIONS_WORK_TYPE_UPDATE = "organizations-work-type:update",

    /** organizations-work-type:delete */
    ORGANIZATIONS_WORK_TYPE_DELETE = "organizations-work-type:delete",

    /** Modules list */
    PERM_MODULES_LIST = "perm_modules:list",

    /** Delete chief architect */
    CHIEF_ARCHITECTS_DELETE = "chief_architects:delete",

    /** Get chief architect */
    CHIEF_ARCHITECTS_GET = "chief_architects:get",

    /** Chief architects list */
    CHIEF_ARCHITECTS_LIST = "chief_architects:list",

    /** Create chief architect */
    CHIEF_ARCHITECTS_CREATE = "chief_architects:create",

    /** Remove document progress */
    DOCUMENT_PROGRESS_REMOVE = "document_progress:remove",

    /** infrastructure:objects_infrastructure_list */
    INFRASTRUCTURE_OBJECTS_INFRASTRUCTURE_LIST = "infrastructure:objects_infrastructure_list",

    /** infrastructure:select */
    INFRASTRUCTURE_SELECT = "infrastructure:select",

    /** infra-types:list */
    INFRA_TYPES_LIST = "infra-types:list",

    /** List document progress by document */
    DOCUMENT_PROGRESS_LIST_BY_DOCUMENT = "document_progress:list_by_document",

    /** Create document progress */
    DOCUMENT_PROGRESS_CREATE = "document_progress:create",

    /** work_type:get */
    WORK_TYPE_GET = "work_type:get",

    /** work_type_progresses:add_progress */
    WORK_TYPE_PROGRESSES_ADD_PROGRESS = "work_type_progresses:add_progress",

    /** Delete contractor */
    CONTRACTORS_DELETE = "contractors:delete",

    /** Update contractor */
    CONTRACTORS_UPDATE = "contractors:update",

    /** Get contractor */
    CONTRACTORS_GET = "contractors:get",

    /** Select contractor */
    CONTRACTORS_SELECT = "contractors:select",

    /** Contractors list */
    CONTRACTORS_LIST = "contractors:list",

    /** Create contractor */
    CONTRACTORS_CREATE = "contractors:create",

    /** Gateway tizimidan tashkilotlarni olish */
    CONSTRUCTOR_LIST = "constructor:list",

    /** Create infrastructure */
    INFRASTRUCTURE_CREATE = "infrastructure:create",

    /** Organization list */
    ORGANIZATIONS_LIST = "organizations:list",

    /** Ruxsatlarni nomlash */
    PERMISSIONS_ADD_DESCRIPTION = "permissions:add_description",

    /** Uchastka yaratish */
    PLOT_CREATE = "plot:create",

    /** Hujjatni olish */
    DOCUMENTS_GET = "documents:get",

    /** Hujjat turlarini yangilash */
    DOCUMENT_CORE_UPDATE = "document-core:update",

    /** Hujjat turini yaratish */
    DOCUMENT_CORE_CREATE = "document-core:create",

    /** Smetalar ro'yxatini olish */
    SMETA_LIST = "smeta:list",

    /** O'lchov birliklarini yangilash */
    MEASUREMENTS_UPDATE = "measurements:update",

    /** O'lchov birliklarini yaratish */
    MEASUREMENTS_CREATE = "measurements:create",

    /** Bitta ish haqida ma'lumot olish olish */
    WORK_GET = "work:get",

    /** Loyiha tafsilotlari uchun rasm yuklash */
    PROJECT_DETAILS_ADD_PHOTO = "project-details:add-photo",

    /** Loyihaga xodimni biriktirish (JSHSHIR ID orqali) */
    OBJECT_ASSIGN_EMPLOYEE = "object:assign_employee",

    /** Bitta loyihani olish */
    OBJECT_GET = "object:get",

    /** Xotiraga faylni yuklash (Umumiy, Global) */
    STORAGE_UPLOAD = "storage:upload",

    /** Uchastkaga xodimId(67071) orqali xodimni biriktirish */
    PLOT_ADD_EMPLOYEE = "plot:add_employee",
}
