// Автосгенерированный клиент API
// Сгенерировано из https://ai-project.das-uty.uz/api/docs-json

import type { paths } from './apiMethods.types';
export const apiMethods = (options?: any) => {
  return {
    App: {
      AppController_getHello: () => useApi<paths['/api/app/exception-test']['get']['responses']['200']>('/api/app/exception-test', { method: 'GET', ...options }),
      AppController_cacheTest: () => useApi<paths['/api/app/cache-test']['get']['responses']['200']>('/api/app/cache-test', { method: 'GET', ...options }),
      AppController_authTest: () => useApi<paths['/api/app/auth-test']['get']['responses']['200']>('/api/app/auth-test', { method: 'GET', ...options }),
    },
    Account: {
      listAccounts: (query?: paths['/api/accounts']['get']['parameters']['query']) => useApi<paths['/api/accounts']['get']['responses']['200']['content']['application/json']>(`/api/accounts`, { method: 'GET', params: query, ...options }),
      createAccount: (body: paths['/api/accounts']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/accounts']['post']['responses']['200']['content']['application/json']>(`/api/accounts`, { method: 'POST', body: body, ...options }),
      getAccountById: (id: string | number) => useApi<paths['/api/accounts/{id}']['get']['responses']['200']['content']['application/json']>(`/api/accounts/${id}`, { method: 'GET', ...options }),
      updateAccount: (id: string | number, body: paths['/api/accounts/{id}']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/accounts/{id}']['put']['responses']['200']>(`/api/accounts/${id}`, { method: 'PUT', body: body, ...options }),
      deleteAccountById: (id: string | number) => useApi<void>(`/api/accounts/${id}`, { method: 'DELETE', ...options }),
      AccountController_getMe: () => useApi<paths['/api/accounts/me']['get']['responses']['200']['content']['application/json']>('/api/accounts/me', { method: 'GET', ...options }),
      addRoleToAccount: (id: string | number, body: paths['/api/accounts/{id}/roles']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/accounts/{id}/roles']['put']['responses']['200']>(`/api/accounts/${id}/roles`, { method: 'PUT', body: body, ...options }),
      AccountController_updateRole: (id: string | number, roleId: string | number, body: paths['/api/accounts/{id}/roles/{roleId}']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/accounts/{id}/roles/{roleId}']['put']['responses']['200']>(`/api/accounts/${id}/roles/${roleId}`, { method: 'PUT', body: body, ...options }),
      removeRoleFromAccount: (id: string | number, roleId: string | number) => useApi<paths['/api/accounts/{id}/roles/{roleId}']['delete']['responses']['200']>(`/api/accounts/${id}/roles/${roleId}`, { method: 'DELETE', ...options }),
    },
    Role: {
      listRoles: (query?: paths['/api/roles']['get']['parameters']['query']) => useApi<paths['/api/roles']['get']['responses']['200']['content']['application/json']>(`/api/roles`, { method: 'GET', params: query, ...options }),
      createRole: (body: paths['/api/roles']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/roles']['post']['responses']['200']['content']['application/json']>(`/api/roles`, { method: 'POST', body: body, ...options }),
      getRole: (id: string | number) => useApi<paths['/api/roles/{id}']['get']['responses']['200']['content']['application/json']>(`/api/roles/${id}`, { method: 'GET', ...options }),
      updateRole: (id: string | number, body: paths['/api/roles/{id}']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/roles/{id}']['put']['responses']['200']['content']['application/json']>(`/api/roles/${id}`, { method: 'PUT', body: body, ...options }),
      deleteRole: (id: string | number) => useApi<void>(`/api/roles/${id}`, { method: 'DELETE', ...options }),
      updateRolePermissions: (id: string | number, body: paths['/api/roles/{id}/permissions']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/roles/{id}/permissions']['post']['responses']['201']>(`/api/roles/${id}/permissions`, { method: 'POST', body: body, ...options }),
    },
    attach: {
      openFile: (fileName: string | number) => useApi<paths['/api/attach/open/{fileName}']['get']['responses']['200']['content']['*/*']>(`/api/attach/open/${fileName}`, { method: 'GET', ...options }),
      uploadFile: (formData: paths['/api/attach/upload']['post']['requestBody']['content']['multipart/form-data']) => useApi<paths['/api/attach/upload']['post']['responses']['201']['content']['application/json']>(`/api/attach/upload`, { method: 'POST', formData: formData, ...options }),
      getAllFiles: (query?: paths['/api/attach']['get']['parameters']['query']) => useApi<paths['/api/attach']['get']['responses']['200']['content']['application/json']>(`/api/attach`, { method: 'GET', params: query, ...options }),
      findOne: (id: string | number) => useApi<paths['/api/attach/{id}']['get']['responses']['200']['content']['application/json']>(`/api/attach/${id}`, { method: 'GET', ...options }),
      deleteAttachment: (id: string | number) => useApi<void>(`/api/attach/${id}`, { method: 'DELETE', ...options }),
      downloadFile: (id: string | number) => useApi<paths['/api/attach/download/{id}']['get']['responses']['200']['content']['*/*']>(`/api/attach/download/${id}`, { method: 'GET', ...options }),
    },
    Auth: {
      login: (body: paths['/api/auth/login']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/auth/login']['post']['responses']['200']['content']['application/json']>(`/api/auth/login`, { method: 'POST', body: body, ...options }),
      deviceLogin: (body: paths['/api/auth/device-login']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/auth/device-login']['post']['responses']['200']['content']['application/json']>(`/api/auth/device-login`, { method: 'POST', body: body, ...options }),
      selectRole: (body: paths['/api/auth/select-role']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/auth/select-role']['post']['responses']['200']['content']['application/json']>(`/api/auth/select-role`, { method: 'POST', body: body, ...options }),
      AuthController_refresh: (body: paths['/api/auth/refresh']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/auth/refresh']['post']['responses']['200']['content']['application/json']>(`/api/auth/refresh`, { method: 'POST', body: body, ...options }),
    },
    Permissions: {
      getAllPermissions: () => useApi<paths['/api/permissions']['get']['responses']['200']['content']['application/json']>('/api/permissions', { method: 'GET', ...options }),
    },
    External_API: {
      findByAllCompany: (query?: paths['/api/external-api/find/companies']['get']['parameters']['query']) => useApi<paths['/api/external-api/find/companies']['get']['responses']['200']['content']['application/json']>(`/api/external-api/find/companies`, { method: 'GET', params: query, ...options }),
    },
    Wagons: {
      findWagonsWithPagination: (query?: paths['/api/wagons']['get']['parameters']['query']) => useApi<paths['/api/wagons']['get']['responses']['200']['content']['application/json']>(`/api/wagons`, { method: 'GET', params: query, ...options }),
      createWagon: (body: paths['/api/wagons']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/wagons']['post']['responses']['201']>(`/api/wagons`, { method: 'POST', body: body, ...options }),
      deleteWagon: (id: string | number) => useApi<void>(`/api/wagons/${id}`, { method: 'DELETE', ...options }),
      getWagonInfoByNumber: (num: string | number) => useApi<paths['/api/wagons/{num}']['get']['responses']['200']>(`/api/wagons/${num}`, { method: 'GET', ...options }),
      checkWagonNumber: (query?: paths['/api/wagons/check/wagon-number']['get']['parameters']['query']) => useApi<paths['/api/wagons/check/wagon-number']['get']['responses']['200']['content']['application/json']>(`/api/wagons/check/wagon-number`, { method: 'GET', params: query, ...options }),
      findByWagonNumber: (wagonNumber: string | number) => useApi<paths['/api/wagons/find-by/{wagonNumber}']['get']['responses']['200']['content']['application/json']>(`/api/wagons/find-by/${wagonNumber}`, { method: 'GET', ...options }),
    },
    bot_user: {
      BotUserController_findAll: (query?: paths['/api/bot-user']['get']['parameters']['query']) => useApi<paths['/api/bot-user']['get']['responses']['200']>(`/api/bot-user`, { method: 'GET', params: query, ...options }),
      BotUserController_create: (body: paths['/api/bot-user']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/bot-user']['post']['responses']['201']>(`/api/bot-user`, { method: 'POST', body: body, ...options }),
      BotUserController_update: (id: string | number, body: paths['/api/bot-user/{id}']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/bot-user/{id}']['put']['responses']['200']>(`/api/bot-user/${id}`, { method: 'PUT', body: body, ...options }),
      BotUserController_delete: (id: string | number) => useApi<void>(`/api/bot-user/${id}`, { method: 'DELETE', ...options }),
    },
    Wagon_Scale_Values: {
      WagonScaleValueController_findPagination: (query?: paths['/api/wagon-scale-values']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values`, { method: 'GET', params: query, ...options }),
      WagonScaleValueController_create: (body: paths['/api/wagon-scale-values']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-scale-values']['post']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values`, { method: 'POST', body: body, ...options }),
      WagonScaleValueController_findMonthlyData: (query?: paths['/api/wagon-scale-values/fullMonthlyData']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/fullMonthlyData']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/fullMonthlyData`, { method: 'GET', params: query, ...options }),
      WagonScaleValueController_update: (id: string | number, body: paths['/api/wagon-scale-values/{id}']['put']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-scale-values/{id}']['put']['responses']['200']>(`/api/wagon-scale-values/${id}`, { method: 'PUT', body: body, ...options }),
      WagonScaleValueController_delete: (id: string | number) => useApi<void>(`/api/wagon-scale-values/${id}`, { method: 'DELETE', ...options }),
      WagonScaleValueController_export: (query?: paths['/api/wagon-scale-values/download/export']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/download/export']['get']['responses']['200']>(`/api/wagon-scale-values/download/export`, { method: 'GET', params: query, ...options }),
      WagonScaleValueController_countByStations: (query?: paths['/api/wagon-scale-values/count-by-stations']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/count-by-stations']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/count-by-stations`, { method: 'GET', params: query, ...options }),
      WagonScaleValueController_countByStation: (organizationId: string | number) => useApi<paths['/api/wagon-scale-values/count-by-stations/{organizationId}']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/count-by-stations/${organizationId}`, { method: 'GET', ...options }),
      WagonScaleValueController_generatePdf: (id: string | number) => useApi<paths['/api/wagon-scale-values/{id}/pdf']['get']['responses']['200']>(`/api/wagon-scale-values/${id}/pdf`, { method: 'GET', ...options }),
      getScaleStatistics: (query?: paths['/api/wagon-scale-values/statistics']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/statistics']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/statistics`, { method: 'GET', params: query, ...options }),
      getScaleIntervalStatistics: (query?: paths['/api/wagon-scale-values/interval-statistics']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/interval-statistics']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/interval-statistics`, { method: 'GET', params: query, ...options }),
      WagonScaleValueController_listCustomScales: (query?: paths['/api/wagon-scale-values/customs']['get']['parameters']['query']) => useApi<paths['/api/wagon-scale-values/customs']['get']['responses']['200']['content']['application/json']>(`/api/wagon-scale-values/customs`, { method: 'GET', params: query, ...options }),
      add_customs_scale_value: (body: paths['/api/wagon-scale-values/customs']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-scale-values/customs']['post']['responses']['201']>(`/api/wagon-scale-values/customs`, { method: 'POST', body: body, ...options }),
      WagonScaleValueController_integration: (body: paths['/api/wagon-scale-values/integration']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-scale-values/integration']['post']['responses']['201']>(`/api/wagon-scale-values/integration`, { method: 'POST', body: body, ...options }),
      WagonScaleValueController_healthCheck: () => useApi<paths['/api/wagon-scale-values/health']['get']['responses']['200']>('/api/wagon-scale-values/health', { method: 'GET', ...options }),
    },
    Sse: {
      SseController_getExtraWeights: () => useApi<paths['/api/sse/extra-weight-alerts']['get']['responses']['200']>('/api/sse/extra-weight-alerts', { method: 'GET', ...options }),
      SseController_sse: () => useApi<paths['/api/sse/test']['get']['responses']['200']>('/api/sse/test', { method: 'GET', ...options }),
      SseController_notify: () => useApi<paths['/api/sse/notify']['post']['responses']['201']>('/api/sse/notify', { method: 'POST', ...options }),
    },
    Organizations: {
      OrganizationsController_syncFromGateway: (body: paths['/api/organizations/sync-from-gateway']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/organizations/sync-from-gateway']['post']['responses']['201']>(`/api/organizations/sync-from-gateway`, { method: 'POST', body: body, ...options }),
      OrganizationsController_getAllOrganizations: (query?: paths['/api/organizations']['get']['parameters']['query']) => useApi<paths['/api/organizations']['get']['responses']['200']['content']['application/json']>(`/api/organizations`, { method: 'GET', params: query, ...options }),
      OrganizationsController_selectOrganizations: (query?: paths['/api/organizations/select']['get']['parameters']['query']) => useApi<paths['/api/organizations/select']['get']['responses']['200']['content']['application/json']>(`/api/organizations/select`, { method: 'GET', params: query, ...options }),
      OrganizationsController_getOrganizationById: (id: string | number) => useApi<paths['/api/organizations/{id}']['get']['responses']['200']['content']['application/json']>(`/api/organizations/${id}`, { method: 'GET', ...options }),
    },
    WagonSession: {
      WagonSessionController_findAll: (query?: paths['/api/wagon-sessions']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions`, { method: 'GET', params: query, ...options }),
      WagonSessionController_create: (body: paths['/api/wagon-sessions']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-sessions']['post']['responses']['201']>(`/api/wagon-sessions`, { method: 'POST', body: body, ...options }),
      WagonSessionController_getIntervalStatistics: (query?: paths['/api/wagon-sessions/interval-statistics']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/interval-statistics']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/interval-statistics`, { method: 'GET', params: query, ...options }),
      WagonSessionController_getStatistics: (query?: paths['/api/wagon-sessions/statistics']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/statistics']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/statistics`, { method: 'GET', params: query, ...options }),
      WagonSessionController_findOne: (id: string | number) => useApi<paths['/api/wagon-sessions/{id}']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/${id}`, { method: 'GET', ...options }),
      WagonSessionController_delete: (id: string | number) => useApi<void>(`/api/wagon-sessions/${id}`, { method: 'DELETE', ...options }),
      WagonSessionController_exportExcel: (id: string | number) => useApi<paths['/api/wagon-sessions/{id}/export-excel']['get']['responses']['200']>(`/api/wagon-sessions/${id}/export-excel`, { method: 'GET', ...options }),
      WagonSessionController_getWagonItems: (id: string | number, query?: paths['/api/wagon-sessions/{id}/items']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/{id}/items']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/${id}/items`, { method: 'GET', params: query, ...options }),
      WagonSessionController_searchWagonNumber: (query?: paths['/api/wagon-sessions/search/by-number']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/search/by-number']['get']['responses']['200']>(`/api/wagon-sessions/search/by-number`, { method: 'GET', params: query, ...options }),
      WagonSessionController_updateWagonNumber: (id: string | number, body: paths['/api/wagon-sessions/{id}/update-number']['patch']['requestBody']['content']['application/json']) => useApi<paths['/api/wagon-sessions/{id}/update-number']['patch']['responses']['200']>(`/api/wagon-sessions/${id}/update-number`, { method: 'PATCH', body: body, ...options }),
      WagonSessionController_deleteWagon: (id: string | number) => useApi<void>(`/api/wagon-sessions/items/${id}`, { method: 'DELETE', ...options }),
      WagonSessionController_countByStations: (query?: paths['/api/wagon-sessions/count/by-stations']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/count/by-stations']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/count/by-stations`, { method: 'GET', params: query, ...options }),
      WagonSessionController_countByStation: (organizationId: string | number) => useApi<paths['/api/wagon-sessions/count/by-station/{organizationId}']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/count/by-station/${organizationId}`, { method: 'GET', ...options }),
      WagonSessionController_handleUpload: (formData: paths['/api/wagon-sessions/upload-video']['post']['requestBody']['content']['multipart/form-data'], query?: paths['/api/wagon-sessions/upload-video']['post']['parameters']['query']) => useApi<paths['/api/wagon-sessions/upload-video']['post']['responses']['201']>(`/api/wagon-sessions/upload-video`, { method: 'POST', formData: formData, params: query, ...options }),
      WagonSessionController_getRailmapTrainStats: (stationCode: string | number, query?: paths['/api/wagon-sessions/railmap/stations/{stationCode}/stats']['get']['parameters']['query']) => useApi<paths['/api/wagon-sessions/railmap/stations/{stationCode}/stats']['get']['responses']['200']['content']['application/json']>(`/api/wagon-sessions/railmap/stations/${stationCode}/stats`, { method: 'GET', params: query, ...options }),
    },
    Camera: {
      CameraController_list: (query?: paths['/api/camera']['get']['parameters']['query']) => useApi<paths['/api/camera']['get']['responses']['200']['content']['application/json']>(`/api/camera`, { method: 'GET', params: query, ...options }),
      CameraController_create: (body: paths['/api/camera/create']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/camera/create']['post']['responses']['201']>(`/api/camera/create`, { method: 'POST', body: body, ...options }),
      CameraController_countByCompanies: (query?: paths['/api/camera/count/by-company']['get']['parameters']['query']) => useApi<paths['/api/camera/count/by-company']['get']['responses']['200']['content']['application/json']>(`/api/camera/count/by-company`, { method: 'GET', params: query, ...options }),
      CameraController_countByCompany: (organizationId: string | number, query?: paths['/api/camera/count/by-company/{organizationId}']['get']['parameters']['query']) => useApi<paths['/api/camera/count/by-company/{organizationId}']['get']['responses']['200']['content']['application/json']>(`/api/camera/count/by-company/${organizationId}`, { method: 'GET', params: query, ...options }),
    },
    Profile: {
      ProfileController_getProfileByPin: (body: paths['/api/profiles/by-pin']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/profiles/by-pin']['post']['responses']['200']['content']['application/json']>(`/api/profiles/by-pin`, { method: 'POST', body: body, ...options }),
    },
    ChatBot: {
      getChatBotSessions: () => useApi<paths['/api/chat-bot/sessions']['get']['responses']['200']['content']['application/json']>('/api/chat-bot/sessions', { method: 'GET', ...options }),
      getChatBotSessionMessages: (sessionId: string | number) => useApi<paths['/api/chat-bot/sessions/{sessionId}/messages']['get']['responses']['200']['content']['application/json']>(`/api/chat-bot/sessions/${sessionId}/messages`, { method: 'GET', ...options }),
      sendMessageToChatBot: (body: paths['/api/chat-bot/send-message']['post']['requestBody']['content']['application/json']) => useApi<paths['/api/chat-bot/send-message']['post']['responses']['200']['content']['application/json']>(`/api/chat-bot/send-message`, { method: 'POST', body: body, ...options }),
    },
  };
};
